HSEARCH-3864 java.lang.Error thrown during mass indexing are swallowed and not reported to the user
hibernate/hibernate-search pull request #2349
Opened 2020-09-04 15:17 UTC by fax4ever

https://hibernate.atlassian.net/browse/HSEARCH-3864

There is some code duplication.
I tried also to make [Make *MassIndexingFailureIT parametric] (https://github.com/fax4ever/hibernate-search/commit/0988a4efa58a8b5164c845f552cf0b0c5a683a86) as alternative...

2020-09-07 13:14 UTC, yrodiere requested changes
Thanks.

There seems to be some problems in the tests. Please fix that first?

2020-09-07 13:14 UTC, yrodiere commented on integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingFailureDefaultBackgroundErrorHandlerIT.java
> +public class MassIndexingFailureDefaultBackgroundErrorHandlerIT extends AbstractMassIndexingErrorIT {
The name of this class looks wrong. It tests behavior when *errors* occur during mass indexing, with the default background *failure* handler. So it should be `MassIndexingErrorDefaultBackgroundFailureHandlerIT`.

2020-09-08 07:25 UTC, fax4ever commented on integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/AbstractMassIndexingErrorIT.java
> +		ERROR;
This is the current behavior:

|                               | AbstractMassIndexingErrorIT | AbstractMassIndexingFailureIT |
|-------------------------------|-----------------------------|-------------------------------|
| indexingAndFlush              | FAIL                        | FAIL                          |
| indexingAndRefresh            | FAIL                        | FAIL                          |
| flush                         | FAIL                        | FAIL                          |
| getId                         | ERROR                       | SKIP                          |
| purge                         | FAIL                        | FAIL                          |
| indexing                      | FAIL                        | FAIL                          |
| refresh                       | FAIL                        | FAIL                          |
| dropAndCreateSchema_exception | FAIL                        | FAIL                          |
| mergeSegmentsAfter            | FAIL                        | FAIL                          |
| mergeSegmentsBefore           | FAIL                        | FAIL                          |
| getTitle                      | ERROR                       | SKIP                          |

`AbstractMassIndexingErrorIT` behaves as `AbstractMassIndexingFailureIT` for all the cases with the exception of `getId` and `getTitle`.
That sounds reasonable to me. If it doesn't sound good for you, what would be the expected behavior?

2020-09-08 10:54 UTC, yrodiere requested changes
See my comments below.

1. The equals/hashcode are probably not a great idea.
2. The duplicated report of the error looked weird. I pushed a few commits to simplify reporting of errors: they are just propagated as-is. Please let me know what you think.

2020-09-08 10:54 UTC, yrodiere commented on mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/MassIndexingFailureContext.java
> +	public boolean equals(Object o) {
Uh no, I don't think it's a good idea to add this just for tests... I don't quite see a use case. Plus you forgot to override equals/hashcode in subclasses.

No, really, let's not do this. If you want to check that `failingOperation` and `throwable` are the same in your test, just do that explicitly? `assertThat( context1.failingOperation() ).isEqualTo( ...)`?

2020-09-08 10:54 UTC, yrodiere commented on integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingErrorDefaultBackgroundFailureHandlerIT.java
> +				.times( 2 );
I wonder why the error is reported twice? There may be a problem here. I'll investigate.

2020-09-08 11:17 UTC, yrodiere commented
I added a few commits to simplify how Errors are reported: we will just propagate them and won't attempt to report them to the failure handlers.
After some discussion on Zulip, we'll go that way.
Let's merge once the build passes.

2020-09-08 11:17 UTC, yrodiere approved these changes

2020-09-08 12:23 UTC, merged

2020-09-08 12:24 UTC, yrodiere commented
Merged, thanks!

2020-09-08 12:24 UTC, fax4ever commented
Thank you!