HSEARCH-4362 Customizable optional operators for the regexp query
hibernate/hibernate-search pull request #2820
Opened 2022-01-05 19:36 UTC by fax4ever

https://hibernate.atlassian.net/browse/HSEARCH-4362

2022-01-05 19:47 UTC, fax4ever commented
Run `default|elasticsearch` build to test more ES versions: https://ci.hibernate.org/blue/organizations/jenkins/hibernate-search/detail/PR-2820/2/pipeline

2022-01-06 09:24 UTC, yrodiere requested changes
Thanks. Here are a few comments.

2022-01-06 09:24 UTC, yrodiere commented on util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/backend/types/impl/StubIndexValueFieldType.java
>  					PredicateTypeKeys.RANGE,
You're assigning the regexp predicate factory to all sorts of predicates that are not the regexp predicate.

The right way to do what you want would be to remove PredicateTypeKeys.REGEXP from the list, and add a call to `stubFactories(new StubSearchPredicate.RegexpFactory(), PredicateTypeKeys.REGEXP)`.

Though TBH, this looks like dead code, so it's more for consistency than anything else.

2022-01-07 10:01 UTC, fax4ever commented
Thanks for the review @yrodiere!
I tried to address the requested changes.

2022-01-07 14:07 UTC, yrodiere approved these changes

2022-01-07 14:07 UTC, merged

2022-01-07 14:08 UTC, yrodiere commented
Merged, thanks!