HSEARCH-4541 Catch load exception and pass to failure handler
hibernate/hibernate-search pull request #3303
Opened 2022-11-07 16:16 UTC by marko-bekhta

https://hibernate.atlassian.net/browse/HSEARCH-4541

I'm not sure if that's what you expected, but while I was trying to create some reproducer of the problem, here are the changes I've made 😄 
The test fails two batches, but the remaining ones are still completed, and in the end, an exception is thrown by `indexer.startAndWait();`
As for the logging of failed IDs, there's already a trace log in place, so I assume that covers it.

2022-11-09 10:17 UTC, yrodiere reviewed
The test looks good, but could you integrate it to `AbstractMassIndexingErrorIT`/`AbstractMassIndexingFailureIT`? You can rely on static switches to trigger the failure only in your test method, see `org.hibernate.search.integrationtest.mapper.orm.massindexing.AbstractMassIndexingFailureIT.Book#failOnBook2GetId`.

You might want to look into the difference between your test and `org.hibernate.search.integrationtest.mapper.orm.massindexing.AbstractMassIndexingFailureIT#entityLoading` and name the test methods accordingly.

>  As for the logging of failed IDs, there's already a trace log in place, so I assume that covers it.

Ideally you would call `org.hibernate.search.mapper.pojo.massindexing.MassIndexingFailureHandler#handle(org.hibernate.search.mapper.pojo.massindexing.MassIndexingEntityFailureContext)`. See `org.hibernate.search.mapper.pojo.massindexing.impl.PojoMassIndexingNotifier#reportEntityIndexingFailure` (though obviously you'll have to do things differently in your case since you don't have an entity instance -- but you might get your hands on an entity reference).

2023-01-04 08:18 UTC, yrodiere requested changes
Thanks! My two cents below.

2023-01-04 08:18 UTC, yrodiere commented on integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingFailureCustomBackgroundFailureHandlerIT.java
> +		verifyNoMoreInteractions( failureHandler );
There's something wrong with indentation.

2023-01-04 09:03 UTC, marko-bekhta commented on integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/AbstractMassIndexingFailureIT.java
> +				SimulatedFailure.class, exceptionMessage, failingOperationAsString, count - 1 );
Hah, I was confused at first too, there're 3 books created with the common test setup, and then the loop in this test is using `<`
```
for ( int i = 4; i < 1500; i++ ) {
```
so the 1500 book is not there

2023-01-04 10:11 UTC, yrodiere commented on integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/AbstractMassIndexingFailureIT.java
> +				SimulatedFailure.class, exceptionMessage, failingOperationAsString, count - 1 );
Ah, good catch. Better use `<=` there, then? And replace the confusing `count - 1` with just `count` :)

2023-01-04 16:21 UTC, yrodiere approved these changes

2023-01-05 12:53 UTC, marko-bekhta commented
ohh same test names for pojo mapper played a joke with me 😄 I was looking at their ORM counterparts and thinking why it works through IDE but not with maven  build. Applied same changes to pojo tests, should be better now 😃

2023-01-09 14:30 UTC, merged