HSEARCH-4938 Remove support for the complement operator
hibernate/hibernate-search pull request #3710
Opened 2023-09-07 08:20 UTC by marko-bekhta

https://hibernate.atlassian.net/browse/HSEARCH-4938

2023-09-10 15:25 UTC, yrodiere commented
@fax4ever Heads-up: we're removing support for the complement (`~`) operator in regexp queries in Hibernate Search 7.0, and I think this will impact Infinispan.

2023-09-10 15:26 UTC, yrodiere requested changes

2023-09-10 15:26 UTC, yrodiere commented on documentation/src/main/asciidoc/public/reference/_search-dsl-predicate.adoc
> -Don't forget to use parentheses if you need to negate a composite pattern, e.g. `+a~(bc)+`
Can you please mention the removal in the migration guide?

2023-09-11 10:09 UTC, fax4ever commented
> complement (`~`

Thank @yrodiere for the update. I need to check it.

2023-09-13 07:24 UTC, yrodiere approved these changes

2023-09-13 07:24 UTC, merged